name: Create release

on:
  workflow_dispatch:
    inputs:
      swift_syntax_tag:
        description: 'The tag to base the release on from the swift-syntax repository.'
        required: true
        type: string

jobs:
  release:
    runs-on: macos-14
    env:
      GITHUB_TOKEN: ${{ github.token }}
      OUTPUT_PATH: SwiftSyntaxPrecompile
      XCFRAMEWORKS_PATH: SwiftSyntaxPrecompile/build/swift-syntax_Precompile/XCFrameworks
      NEW_SWIFT_SYNTAX_PATH: SwiftSyntaxPrecompile/build/swift-syntax_Precompile/XCFrameworks/packages/swift-syntax

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.0.0

    - run: |
        xcode-select -p
        unzip scipio.zip
        ls -l
        chmod +x scipio
        ./scipio precompile remote \
          --upload-url https://github.com/${{ github.repository }}/releases/download/${{ inputs.swift_syntax_tag }} \
          -i https://github.com/swiftlang/swift-syntax \
          -i tag=${{ inputs.swift_syntax_tag }} \
          -o SwiftSyntaxPrecompile \
          -p "swift-syntax" \
          -v

    - run: |
        rm -Rf Sources
        rm -f Packages.swift
        cp -r ${{ env.NEW_SWIFT_SYNTAX_PATH }}/Sources .
        cp ${{ env.NEW_SWIFT_SYNTAX_PATH }}/Package.swift .
      
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updated for release ${{ inputs.swift_syntax_tag }}
        tagging_message: ${{ inputs.swift_syntax_tag }}
        file_pattern: "*.swift Sources/*"
    - uses: softprops/action-gh-release@v1
      with:
        draft: false
        name: ${{ inputs.swift_syntax_tag }}
        tag_name: ${{ inputs.swift_syntax_tag }}
        body: Release from swift-syntax ${{ inputs.swift_syntax_tag }}
        files: "*.xcframework.zip"
        fail_on_unmatched_files: true
