name: Create release

on:
  workflow_dispatch:
    inputs:
      swift_syntax_tag:
        description: 'The tag to base the release on from the swift-syntax repository.'
        required: true
        type: string

jobs:
  release:
    runs-on: macos-14
    # runs-on: ghcr.io/cirruslabs/macos-runner:sonoma
    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ github.token }}
      OUTPUT_PATH: SwiftSyntaxPrecompile
      XCFRAMEWORKS_PATH: SwiftSyntaxPrecompile/build/swift-syntax_Precompile/XCFrameworks
      NEW_SWIFT_SYNTAX_PATH: SwiftSyntaxPrecompile/build/swift-syntax_Precompile/XCFrameworks/packages/swift-syntax
      SCIPIO_COMMIT: 14185fc

    timeout-minutes: 60 # Increase this timeout value as needed

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    # - name: Collect Workflow Telemetry
    #   uses: catchpoint/workflow-telemetry-action@v2
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Setup Git authentication
    #   run: |
    #     git config --global user.name "github-actions"
    #     git config --global user.email "github-actions@github.com"
    #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/username/repo.git
    # - run: |
    #     git clone https://github.com/yume190/TypeFill
    # - run: |
    #     ls -al
    #     pwd
    #     cd TypeFill && \
    #     git checkout 8d85559

    # - run: |
    #     git clone https://github.com/PreternaturalAI/Scipio && \
    #     cd Scipio && \
    #     git checkout 3fb4684 && \
    #     swift build 
        
    #     swift run --package-path Scipio precompile remote \
    #       --upload-url https://github.com/${{ github.repository }}/releases/download/${{ inputs.swift_syntax_tag }} \
    #       -i https://github.com/swiftlang/swift-syntax \
    #       -i tag=${{ inputs.swift_syntax_tag }} \
    #       -o ${{ env.OUTPUT_PATH}} \
    #       -p "swift-syntax" \
    #       -v 2>&1


    - run: |
        arch
        xcode-select -p
        unzip scipio.zip
        ls -l
        chmod +x scipio
        ./scipio precompile remote \
          --upload-url https://github.com/${{ github.repository }}/releases/download/${{ inputs.swift_syntax_tag }} \
          -i https://github.com/swiftlang/swift-syntax \
          -i tag=${{ inputs.swift_syntax_tag }} \
          -o ${{ env.OUTPUT_PATH}} \
          -p "swift-syntax" \
          -v \
          2>&1

# --enable-library-evolution

    - run: |
        rm -Rf Sources
        rm -f Packages.swift
        cp -r ${{ env.NEW_SWIFT_SYNTAX_PATH }}/Sources .
        cp ${{ env.NEW_SWIFT_SYNTAX_PATH }}/Package.swift .
        ls -l
      
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updated for release ${{ inputs.swift_syntax_tag }}
        tagging_message: ${{ inputs.swift_syntax_tag }}
        file_pattern: "Package.swift Sources/*"
    - uses: softprops/action-gh-release@v1
      with:
        draft: false
        name: ${{ inputs.swift_syntax_tag }}
        tag_name: ${{ inputs.swift_syntax_tag }}
        body: Release from swift-syntax ${{ inputs.swift_syntax_tag }}
        files: "${{ env.XCFRAMEWORKS_PATH }}/*.xcframework.zip"
        fail_on_unmatched_files: true
